### ISSUE TITLE
wrong package name?

### ISSUE THREAD

**Issue by roeierez** [status-im/doubleratchet#7]
Hi, 
Thanks for this repository, we like it.
We have noticed you converted it from github.com/tiabc/doubleratchet and right now in the glide.yaml this name still exists as the package name.
Also in the readme it still occurs on the headers encryption example.
Thanks a lot.

**Comment by david415** [comment]
indeed you must fix your readme to actually link to the correct api docs url. come on dudes!

**Comment by cammellos** [comment]
Well spotted, thanks
